[project]
name = "registro-electoral-venezuela"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "invoke>=2.2.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "streamlit>=1.38.0",
]
